// <auto-generated />
using Emp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Emp.Migrations
{
    [DbContext(typeof(EmpDBContext))]
    [Migration("20180311214558_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Emp.Model.EvidenciaZamestnanca", b =>
                {
                    b.Property<int>("EvidenciaZamestnancaID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumNastupu");

                    b.Property<DateTime?>("DatumUkoncenia");

                    b.Property<float>("Plat");

                    b.Property<int>("PoziciaID");

                    b.Property<int>("ZamestnanecID");

                    b.HasKey("EvidenciaZamestnancaID");

                    b.HasIndex("PoziciaID");

                    b.HasIndex("ZamestnanecID");

                    b.ToTable("EvidenciaZamestnancov");
                });

            modelBuilder.Entity("Emp.Model.Pozicia", b =>
                {
                    b.Property<int>("PoziciaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazov")
                        .IsRequired();

                    b.Property<bool>("Vymazana");

                    b.HasKey("PoziciaID");

                    b.ToTable("Pozicie");
                });

            modelBuilder.Entity("Emp.Model.Zamestnanec", b =>
                {
                    b.Property<int>("ZamestnanecID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa");

                    b.Property<DateTime>("DatumNarodenia");

                    b.Property<string>("Meno")
                        .IsRequired();

                    b.Property<string>("Priezvisko")
                        .IsRequired();

                    b.HasKey("ZamestnanecID");

                    b.ToTable("Zamestnanci");
                });

            modelBuilder.Entity("Emp.Model.EvidenciaZamestnanca", b =>
                {
                    b.HasOne("Emp.Model.Pozicia", "Pozicia")
                        .WithMany()
                        .HasForeignKey("PoziciaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Emp.Model.Zamestnanec", "Zamestnanec")
                        .WithMany()
                        .HasForeignKey("ZamestnanecID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
